project: ""
rancher:
  clusterId: ""
  projectId: ""

repository:

branches: []

webhook:
  tokenSecretName: ci-webhook-token
  tokenSecretKey: token
  createSecret: false

kubectl:
  server: ""
  tokenSecretName: k8s
  tokenSecretKey: token
  tokenSecretValue: ""

jobs:
  namespace:
  customSecretName: jobs-secrets
  customSecretValues: {}

labels: {}

env: {}

replicaCount: 1

deploy:
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci
  tag: latest
  pullPolicy: Always
  pullSecret: "registry-creds"

pushRunner:
  image: registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/push-runner
  tag: latest
  command: .k8sci/run.sh


nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: webhook-receiver.chart.local
      paths:
        - /
  tls: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}