project: emjpm
rancher:
  clusterId: c-bd7z2
  projectId: p-57mxc
repository: https://github.com/SocialGouv/emjpm
kubectl:
  server: https://rancher.fabrique.social.gouv.fr/k8s/clusters/c-bd7z2
ingress:
  enabled: true
  hosts:
    - host: ci-emjpm.dev2.fabrique.social.gouv.fr
      paths:
        - /
  tls:
    - hosts:
      - ci-emjpm.dev2.fabrique.social.gouv.fr
      secretName: wildcard-crt

branches:
  - next
  - prod
  - apitest
  - demo
  - receipt

