project: emjpm
rancher:
  clusterId: c-gjtkk
  projectId: p-74q7c
repository: https://github.com/SocialGouv/emjpm
kubectl:
  server: https://rancher.fabrique.social.gouv.fr/k8s/clusters/c-gjtkk
ingress:
  enabled: true
  hosts:
    - host: ci-emjpm.dev.fabrique.social.gouv.fr
      paths:
        - /
  tls:
    - hosts:
      - ci-emjpm.dev.fabrique.social.gouv.fr
      secretName: wildcard-crt

branches:
  - prod
  - ".*\\.dev"

