#!/bin/sh
set -e

TAG=$1
if [ -n "$TAG" ]; then
  docker build -t harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/kail:$TAG kail
  docker push harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/kail:$TAG
fi
docker build -t harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/kail kail
docker push harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/kail
