#!/bin/sh

TAG=$1
if [ -n "$TAG" ]; then
  docker build -t registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/push-runner:$TAG push-runner
  docker push registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/push-runner:$TAG
fi
docker build -t registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/push-runner:latest push-runner
docker push registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/push-runner:latest
