#!/bin/sh
set -e

TAG=$1
if [ -n "$TAG" ]; then
  docker build -t harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/runner:$TAG runner
  docker push harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/runner:$TAG
fi
docker build -t harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/runner runner
docker push harbor.fabrique.social.gouv.fr/emjpm/k8s-ci/runner
