#!/bin/sh
set -e

TAG=$1
if [ -n "$TAG" ]; then
  docker build -t harbor.fabrique.social.gouv.fr/emjpm/k8s-ci:$TAG .
  docker push harbor.fabrique.social.gouv.fr/emjpm/k8s-ci:$TAG
fi
docker build -t harbor.fabrique.social.gouv.fr/emjpm/k8s-ci .
docker push harbor.fabrique.social.gouv.fr/emjpm/k8s-ci
