#!/bin/sh
set -e

TAG=$1
if [ -n "$TAG" ]; then
  docker build -t registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/runner:$TAG runner
  docker push registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/runner:$TAG
fi
docker build -t registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/runner:latest runner
docker push registry.gitlab.factory.social.gouv.fr/socialgouv/sre/k8s-ci/runner:latest
