#!/bin/sh

set -e

export K8SCI_ACTION=${K8SCI_ACTION:-"$1"}
export K8SCI_CONTEXT=${K8SCI_CONTEXT:-"$2"}
export K8SCI_GID=${K8SCI_GID:-"$(uuidgen)"}

if [ -z "$K8SCI_ACTION" ]; then
  echo "missing 1 required argument or K8SCI_ACTION env var"
  exit 1
fi

jobs="[]"

runJob() {
  job="{}"
  job=$(echo $job | jq -rc --arg a "$K8SCI_JOB_ID" '.id = $a')
  job=$(echo $job | jq -rc --arg a "$CI_CONTEXT" '.context = $a')
  K8SCI_ACTION=$(echo $K8SCI_ACTION | sed 's/\.//g') # dot dot attack protection
  if ! [ -f /opt/jobs/${K8SCI_ACTION}/create.sh ]; then
    job=$(echo $job | jq -rc --arg a "unkown action: ${K8SCI_ACTION}" '.message = $a')
    job=$(echo $job | jq -rc --arg a "error" '.status = $a')
    jobs=$(echo $jobs | jq -r ". |= .+ [$job]")
    return 1
  fi
  if result=$(/opt/jobs/${K8SCI_ACTION}/create.sh 2>&1); then
    job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
    job=$(echo $job | jq -rc --arg a "success" '.status = $a')
    jobs=$(echo $jobs | jq -r ". |= .+ [$job]")
  else
    job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
    job=$(echo $job | jq -rc --arg a "error" '.status = $a')
    jobs=$(echo $jobs | jq -r ". |= .+ [$job]")
    return 1
  fi
}

if [ -n "$K8SCI_CONTEXT" ]; then
  K8SCI_CONTEXT_LIST=$K8SCI_CONTEXT
  for context in $(echo $K8SCI_CONTEXT_LIST | sed "s/,/ /g"); do
    export K8SCI_CONTEXT=$context
    runJob || break
  done
else
  runJob
fi

echo '{}' | jq -rc ".jobs = $jobs" | jq -rc ".gid = $K8SCI_JOB_ID"
