#!/bin/sh

set -e

export JOB_NAME=$1

export K8SCI_GID=$(date +'%s%3N')

if [ "$K8SCI_REF_TYPE" = "branch" ]; then
  export K8SCI_BRANCH=${K8SCI_REF}
else
  export K8SCI_BRANCH=$(echo $K8SCI_REF | cut -d / -f3-)
fi


job="{}"
job=$(echo $job | jq -rc --arg a "$K8SCI_GID" '.id = $a')
if result=$(cat "/opt/jobs/${JOB_NAME}.yaml" | gomplate | \
  kubectl -n $K8SCI_K8S_NS create -f - 2>&1); then
  job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
  job=$(echo $job | jq -rc --arg a "success" '.status = $a')
  jobs=$(echo $jobs | jq -r ". |= .+ [$job]")
else
  job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
  job=$(echo $job | jq -rc --arg a "error" '.status = $a')
fi

echo '{}' | jq -rc ".job = $job"
