#!/bin/sh

mkdir -p /.kube
cd /.kube

export K8SCI_KUBECONFIG=${K8SCI_KUBECONFIG:-/.kube/config}
mkdir -p $(dirname $K8SCI_KUBECONFIG)
touch $K8SCI_KUBECONFIG

export KUBECONFIG="${K8SCI_KUBECONFIG}:${KUBECONFIG}"

kubectl config set-credentials k8sci --token=$K8SCI_K8S_TOKEN
kubectl config set-cluster k8sci --server=$K8SCI_K8S_SERVER
kubectl config set-context k8sci --cluster k8sci --user k8sci
kubectl config use-context k8sci