#!/bin/bash

set -e

export JOB_ID=$(uuidgen)

job="{}"
job=$(echo $job | jq -rc --arg a "$JOB_ID" '.id = $a')
if result=$(/opt/jobs/push/create.sh 2>&1); then
  job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
  job=$(echo $job | jq -rc --arg a "success" '.status = $a')
  jobs=$(echo $jobs | jq -r ". |= .+ [$job]")
else
  job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
  job=$(echo $job | jq -rc --arg a "error" '.status = $a')
fi

case $K8SCI_OUTPUT in
  id)
    echo $JOB_ID
    ;;
  json | *)
    echo '{}' | jq -rc ".job = $job"
    ;;
esac