#!/bin/sh

set -e

export JOB_NAME=$1

export K8SCI_GID=$(uuidgen)

job="{}"
job=$(echo $job | jq -rc --arg a "$K8SCI_GID" '.id = $a')
if result=$(/opt/jobs/${JOB_NAME}/create.sh 2>&1); then
  job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
  job=$(echo $job | jq -rc --arg a "success" '.status = $a')
  jobs=$(echo $jobs | jq -r ". |= .+ [$job]")
else
  job=$(echo $job | jq -rc --arg a "$result" '.message = $a')
  job=$(echo $job | jq -rc --arg a "error" '.status = $a')
fi

echo '{}' | jq -rc ".job = $job"
