kind: ConfigMap
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "webhook-receiver.fullname" . }}
  labels:
    {{- include "webhook-receiver.labels" . | nindent 4 }}
data:
  kubectltoken: {{ required "kubectl.tokenSecretName must be specified" .Values.kubectl.tokenSecretName }}
  hooks.yaml: |
    - id: push
      execute-command: /opt/hooks/push
      trigger-rule:
        and:
          - or: # token match
            - match: # url ?token=
                type: value
                value: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: url
                  name: token
            - match: # github webhook
                type: payload-hmac-sha1
                secret: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: header
                  name: X-Hub-Signature
            - match: # gitlab webhook
                type: value
                value: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: header
                  name: X-Gitlab-Token
            - match: # gitea webhook
                type: value
                value: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: payload
                  name: secret
          {{ if ne (len .Values.branches) 0 }}
          - or: # webhook branches
            {{ range $i, $branch := .Values.branches }}
            - match:
                type: value
                value: refs/heads/{{ $branch }}
                parameter:
                  source: payload
                  name: ref
            {{ end }}
            - match:
                type: regex
                regex: .*
                parameter:
                  source: url
                  name: branch
          {{ end }}
      command-working-directory: /opt
      response-headers:
        - name: Content-Type
          value: application/json
      include-command-output-in-response: true
      pass-environment-to-command:
        - source: payload
          name: ref
          envname: K8SCI_REF
        - source: url
          name: branch
          envname: K8SCI_BRANCH
    - id: delete
      execute-command: /opt/hooks/delete
      pass-arguments-to-command:
        - type: value
          value: delete
      trigger-rule:
        and:
          - or: # token match
            - match: # url ?token=
                type: value
                value: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: url
                  name: token
            - match: # github webhook
                type: payload-hmac-sha1
                secret: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: header
                  name: X-Hub-Signature
            - match: # gitlab webhook
                type: value
                value: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: header
                  name: X-Gitlab-Token
            - match: # gitea webhook
                type: value
                value: '{{"{{"}} getenv "K8SCI_WEBHOOK_TOKEN" | js {{"}}"}}'
                parameter:
                  source: payload
                  name: secret
      command-working-directory: /opt
      response-headers:
        - name: Content-Type
          value: application/json
      include-command-output-in-response: true
      pass-environment-to-command:
        - source: payload
          name: ref
          envname: K8SCI_REF
        - source: url
          name: branch
          envname: K8SCI_BRANCH

    - id: status
      execute-command: /opt/k8sci-status
      response-message: Online
      include-command-output-in-response: true
