apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "webhook-receiver.fullname" . }}
  labels:
    {{- include "webhook-receiver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "webhook-receiver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        timestamp: "{{ now | date "20060102150405" }}"
      labels:
        {{- include "webhook-receiver.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "webhook-receiver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      imagePullSecrets:
      - name: {{ .Values.deploy.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/sh
            - -c
            - |
              /opt/k8sci-init-kubeconfig
              /usr/local/bin/webhook \
                -hooks=/etc/webhook/hooks.yaml \
                -hotreload \
                -template
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.deploy.image }}:{{ .Values.deploy.tag }}"
          imagePullPolicy: {{ .Values.deploy.pullPolicy }}
          env:
          {{- range $pkey, $pval := .Values.env }}
          - name: {{ $pkey }}
            value: {{ quote $pval }}
          {{- end }}
          # SPECIFIC TO CI ENV FROM VALUES
          - name: K8SCI_PROJECT
            value: {{ required "project must be specified" .Values.project }}
          - name: K8SCI_WEBHOOK_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ required "webhook.tokenSecretName must be specified" .Values.webhook.tokenSecretName }}
                key: {{ .Values.webhook.tokenSecretKey }}
          - name: K8SCI_K8S_NS
            value: {{ default .Values.jobs.namespace .Release.Namespace }}
          - name: K8SCI_K8S_SERVER
            value: {{ required "kubectl.server must be specified" .Values.kubectl.server }}
          - name: K8SCI_K8S_TOKEN_SECRET_NAME
            value: {{ required "kubectl.tokenSecretName must be specified" .Values.kubectl.tokenSecretName }}
          - name: K8SCI_K8S_TOKEN_SECRET_KEY
            value: {{ .Values.kubectl.tokenSecretKey }}
          - name: K8SCI_K8S_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ required "kubectl.tokenSecretName must be specified" .Values.kubectl.tokenSecretName }}
                key: {{ .Values.kubectl.tokenSecretKey }}
          - name: K8SCI_REPOSITORY
            value: {{ required "repository must be specified" .Values.repository }}
          - name: K8SCI_PUSH_RUNNER_IMAGE
            value: {{ .Values.webhookRunner.image }}
          - name: K8SCI_PUSH_RUNNER_TAG
            value: {{ .Values.webhookRunner.tag }}
          - name: K8SCI_PUSH_RUNNER_COMMAND
            value: {{ .Values.webhookRunner.commands.push }}
          - name: K8SCI_DELETE_RUNNER_COMMAND
            value: {{ .Values.webhookRunner.commands.delete }}
          - name: K8SCI_CUSTOM_SECRET_NAME
            value: {{ .Values.jobs.customSecretName }}
          - name: KUBECONFIG
            value: /.kube/config
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /hooks/status
              port: http
          readinessProbe:
            httpGet:
              path: /hooks/status
              port: http
          volumeMounts:
            - name: configs
              mountPath: "/etc/webhook/hooks.yaml"
              subPath: "hooks.yaml"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: configs
          configMap:
            name: {{ include "webhook-receiver.fullname" $ }}
            defaultMode: 0755
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
