apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace }}
  name: jobs-cleanup
  labels:
    {{- include "webhook-receiver.labels" . | nindent 4 }}
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl-container
            image: bitnami/kubectl:latest
            env:
            - name: K8S_SERVER
              value: {{ required "kubectl.server must be specified" .Values.kubectl.server }}
            - name: K8S_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ required "kubectl.tokenSecretName must be specified" .Values.kubectl.tokenSecretName }}
                  key: {{ .Values.kubectl.tokenSecretKey }}
            command:
              - sh
              - -c
              - |
                kubectl \
                  --namespace {{ default .Values.jobs.namespace .Release.Namespace }} \
                  --server $K8S_SERVER \
                  --token $K8S_TOKEN \
                  delete jobs \
                    --field-selector status.successful=1

                FAILED_JOBS=$(kubectl \
                  --namespace {{ default .Values.jobs.namespace .Release.Namespace }} \
                  --server $K8S_SERVER \
                  --token $K8S_TOKEN \
                  get jobs -o=jsonpath='{.items[?(@.status.conditions[0].type=="Failed")].metadata.name}')
                if [ -n "$FAILED_JOBS" ]; then
                  kubectl \
                    --namespace {{ default .Values.jobs.namespace .Release.Namespace }} \
                    --server $K8S_SERVER \
                    --token $K8S_TOKEN \
                    delete jobs \
                      $FAILED_JOBS
                fi


          restartPolicy: Never