{{- if .Values.webhook.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.webhook.tokenSecretName }}
data:
  {{ .Values.webhook.tokenSecretKey }}: {{ randAlphaNum 20 | b64enc }}
{{ end }}

{{- if .Values.kubectl.tokenSecretValue }}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.kubectl.tokenSecretName }}
data:
  {{ .Values.kubectl.tokenSecretKey }}:  {{ .Values.kubectl.tokenSecretValue | b64enc }}
{{ end }}